---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ${CILIUM_LB_POOL_NAME:-default-pool}
spec:
  blocks:
    - start: ${CILIUM_LB_IP_START}
      stop: ${CILIUM_LB_IP_STOP}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ${CILIUM_L2_POLICY_NAME:-default-l2-announcement-policy}
  namespace: ${CILIUM_NAMESPACE:-kube-system}
spec:
  externalIPs: true
  loadBalancerIPs: true
